# Generated by Django 5.2 on 2025-04-24 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identitydocument',
            name='user',
        ),
        migrations.CreateModel(
            name='PieceIdentite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PASSPORT', 'Passeport'), ('PERMIS', 'Permis de conduire')], max_length=100)),
                ('image', models.ImageField(upload_to='pieces_identite/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenoms', models.CharField(blank=True, max_length=200)),
                ('date_naissance', models.CharField(blank=True, max_length=20)),
                ('date_expiration', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('VALIDÉ', 'Validé'), ('REJETÉ', 'Rejeté')], default='SOUMIS', max_length=10)),
                ('commentaire_validation', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='IdentityDocument',
        ),
    ]
